### ISSUE TITLE
the meaning of the Rectified_max.png

### ISSUE THREAD

**Issue by 9435LV** [rafael-weilharter/HAMMER#1]
I greatly admire you for doing such an amazing job.
I find that in your test.py, when fusion the dtu. The /rect_{:0>3}_max.png could not be found in the data dataset.
`if(args.dataset=="blended_mvs"):
            ref_img = read_img(os.path.join(scan_folder, 'blended_images/{:0>8}.jpg'.format(ref_view)))
        elif (args.dataset=="dtu_full_res"):
            ref_img = read_img(os.path.join(args.testpath, "Rectified/" + scan_name + '/rect_{:0>3}_max.png'.format(ref_view+1)))
        else:
            ref_img = read_img(os.path.join(scan_folder, 'images/{:0>8}.jpg'.format(ref_view)))`

**Comment by rafael-weilharter** [comment]
Hey, thank you!

The _max images should be part of the DTU dataset, indicating max lighting. They are very similar to the _3_r5000 ones though.
